### ISSUE TITLE
Multilabel classification 

### ISSUE THREAD

**Issue by abhigoku10** [IBM/CrossViT#1]
@jjasghar @krook @chunfuchen  thanks a lot for sharing the code , i have a problem statement which i want to train crossvit on please find the details below 
1. input is of image shape 256x128 having label vector as gt for multilabel classification 
2. can i use crossvit to train the model , what all modification has to be done with the code base ??

THnaks for the support

**Comment by jjasghar** [comment]
🤷‍♀️ I'm not sure, this is completely out of my skill set. Maybe @chunfuchen can help out here?

**Comment by chunfuchen** [comment]
@abhigoku10 
This repo is to reproduce our results in the paper. We won't be able to provide too much guidance out of that scope.

However, here are my two cents:
For multi-label classification, you can follow the practices of how do people resolve such problems based on CNN. Our model generates a feature vector before the classification. For the different input sizes, you can either pad/resize them into 240x240.

**Comment by abhigoku10** [comment]
@chunfuchen  thanks ofr your response will take your suggestion and try

**Comment by chunfuchen** [comment]
closed, please feel free to re-open if you have any other questions
